### PR TITLE
Cpp option ghc92

### LINKED ISSUE #42: Cannot compile with ghc 9.2 because of use of Option datatype
Seems still to be using deprecated (now removed) Option.

```
[ 2 of 11] Compiling Data.Monoid.DecidablyEmpty ( src/Data/Monoid/DecidablyEmpty.hs, dist/build/Data/Monoid/DecidablyEmpty.o, dist/build/Data/Monoid/DecidablyEmpty.dyn_o )

src/Data/Monoid/DecidablyEmpty.hs:72:41: error:
    Not in scope: type constructor or class ‘Option’
   |
72 | instance Semigroup a => DecidablyEmpty (Option a) where
   |                                         ^^^^^^

src/Data/Monoid/DecidablyEmpty.hs:73:12: error:
    Not in scope: data constructor ‘Option’
   |
73 |   isEmpty (Option a) = isNothing a
   |            ^^^^
```

Other projects have used CPP for this - don't know if preference is to remove or use CPP.

### PR DESCRIPTION
**Pull request by endgame**
Closes #42.

Also tidied up `-XStarIsType` warnings, raised bounds, and synchronised the CI matrix with what's listed in `tested-with:`.

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
Thank you!! Sorry I did not see this before.
