### ISSUE TITLE
Cannot compile with ghc 9.2 because of use of Option datatype

### ISSUE THREAD

**Issue by emberdart** [reflex-frp/patch#42]
Seems still to be using deprecated (now removed) Option.

```
[ 2 of 11] Compiling Data.Monoid.DecidablyEmpty ( src/Data/Monoid/DecidablyEmpty.hs, dist/build/Data/Monoid/DecidablyEmpty.o, dist/build/Data/Monoid/DecidablyEmpty.dyn_o )

src/Data/Monoid/DecidablyEmpty.hs:72:41: error:
    Not in scope: type constructor or class ‘Option’
   |
72 | instance Semigroup a => DecidablyEmpty (Option a) where
   |                                         ^^^^^^

src/Data/Monoid/DecidablyEmpty.hs:73:12: error:
    Not in scope: data constructor ‘Option’
   |
73 |   isEmpty (Option a) = isNothing a
   |            ^^^^
```

Other projects have used CPP for this - don't know if preference is to remove or use CPP.

**Comment by Ericson2314** [comment]
CPP would be good.

**Comment by emberdart** [comment]
Awesome, thanks, didn't catch this until now. Will try the later deps on later versions.
